### ISSUE TITLE
Could you please send me the dataset and training weights? Thank you very, very much.

### ISSUE THREAD

**Issue by inever789** [robert80203/HuPR-A-Benchmark-for-Human-Pose-Estimation-Using-Millimeter-Wave-Radar#1]
I am a master student in Chongqing Research Institute of Beijing Institute of Technology. My research direction is millimeter wave radar sign language recognition, and this project is closely related to my research direction. However, I could not open the download link provided by the author. Could you please send the dataset and training weight to my email address, 1243250363@qq.com? I really need this material, thank you again.

**Comment by robert80203** [comment]
Hi, we only share our dataset and weights via Google drive.  Please click the dataset link to download the data with the required information.
