### ISSUE TITLE
Dataset access

### ISSUE THREAD

**Issue by Ericwen2001** [robert80203/HuPR-A-Benchmark-for-Human-Pose-Estimation-Using-Millimeter-Wave-Radar#16]
Thanks for opensoucing this benchmark and dataset.
Can you please try to fix the 404 Not Found error in the Google Drive link? I tried to fill out the form last week but received no response and can not access the form again because of the 404 error.

**Comment by dev-sora** [comment]
Hi HuPR team, I'm suffering from the same problem mentioned above.

**Comment by zhangyingyuaaa** [comment]
Hi, can you try to fix the 404 Not Found error in Google Drive link。

**Comment by robert80203** [comment]
We have been tried to fix the link.
Once it gets fixed, we will update the github page.
