### ISSUE TITLE
Access about the dataset

### ISSUE THREAD

**Issue by Carbord** [robert80203/HuPR-A-Benchmark-for-Human-Pose-Estimation-Using-Millimeter-Wave-Radar#2]
Hello! It is an impressive work. I have sent the request to the access to Google Drive of the public dataset a few days ago. But I did not get any contact. Would you be kind to share the dataset link for downloading?

**Comment by huiqx** [comment]
I'm having the same issue. Could you go through my request or share the dataset link for downloading?  Thank you so much.
