### ISSUE TITLE
I can't find these two files：hrnet_annot.json and test.yaml

### ISSUE THREAD

**Issue by inever789** [robert80203/HuPR-A-Benchmark-for-Human-Pose-Estimation-Using-Millimeter-Wave-Radar#3]
I can not find the file of hrnet_annot.json in data/HuPR /single_/annot when running  process_iwr1843.py
and also can not the file  of test.yaml in config/20211106/test.yaml when running main.py
Do these two files need to be generated by themselves？
Thank you very much.

**Comment by robert80203** [comment]
Please find annotation files in the drive and use mscsa_prgcn.yaml instead.
