### ISSUE TITLE
May I ask whether the pre-training weight “model_best.pth” you provided is damaged?

### ISSUE THREAD

**Issue by inever789** [robert80203/HuPR-A-Benchmark-for-Human-Pose-Estimation-Using-Millimeter-Wave-Radar#5]
![image](https://user-images.githubusercontent.com/111219442/217165014-0f95d049-afc3-47a9-9816-15b4cf7cff01.png)
The above error occurred during testing.

**Comment by robert80203** [comment]
The correct pre-trained weight has been updated. Please download it from the link again.

**Comment by inever789** [comment]
Okk, thank you very much!
