### ISSUE TITLE
RF-Pose implementation

### ISSUE THREAD

**Issue by duyddwcs** [robert80203/HuPR-A-Benchmark-for-Human-Pose-Estimation-Using-Millimeter-Wave-Radar#7]
Could you share your implementation of RF-Pose please?

**Comment by robert80203** [comment]
Hi,
We simply followed the implementation described in RF-Pose.
The input for RF-Pose is generated by MNet which combine chirps into one single frame.
Hope this will help you.

**Comment by Hungtran-pro** [comment]
Hi @robert80203 ,

I tried to implement RF-Pose as you said to put it right after MNet (which has output shape is: 20, 32, 24, 64, 64) (I increased numGroupFrame to 24 also). But when I apply it to RF_Encoder, it doesn't work well. The Conv3D and Stride only shrunk the data, it couldn't run through 10 encoding layers. Could you let me know where I was wrong? Or do I need to change the data-processing?
